language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules

install:
  - npm install
  - npm run client:init

before_script:
  - npm run build
script:
  - npm run test:client
on:
  branch: master

after_success:
  - npm run coverage
services:
