const questionData = [
  {
    isRequired: true,
    _id: "5c2f96eba3f926162eb15bc3",
    supportType: "5c2f96eba3f926162eb15bc2",
    questionText: "Please select your area(s) of wellness",
    inputType: "checkbox",
    helperText: "You can select as many as you like",
    options: [
      "Emotional",
      "Social",
      "Physical",
      "Financial",
      "Spiritual",
      "Intellectual",
      "Environmental",
      "Occupational",
    ],
    section: "Support Details",
    __v: 0,
  },
  {
    isRequired: true,
    _id: "5c2f96eba3f926162eb15bc4",
    supportType: "5c2f96eba3f926162eb15bc2",
    questionText: "Registered organisation name",
    inputType: "text",
    section: "Admin Info",
    __v: 0,
  },
  {
    isRequired: true,
    _id: "5c2f96eba3f926162eb15bc5",
    supportType: "5c2f96eba3f926162eb15bc2",
    questionText: "Registered address",
    inputType: "address",
    section: "Admin Info",
    __v: 0,
  },
  {
    isRequired: false,
    _id: "5c2f96eba3f926162eb15bc6",
    supportType: "5c2f96eba3f926162eb15bc2",
    questionText:
      "Please list all relevant regulation, registration and membership bodies and numbers",
    inputType: "textarea",
    section: "Admin Info",
    __v: 0,
  },
  {
    isRequired: true,
    _id: "5c2f96eba3f926162eb15bc7",
    supportType: "5c2f96eba3f926162eb15bc2",
    questionText: "What best describes your core service offering?",
    helperText: "Check all that apply to your core offering",
    options: [
      "Qualified therapy or counselling service",
      "Practical support",
      "Financial support",
      "Legal support",
      "Information and education",
      "Guidance and advice",
      "Self-help",
      "Other emotional support",
      "Product",
      "Activities",
      "Other",
    ],
    inputType: "radio",
    section: "Basic Info",
    __v: 0,
  },
  {
    isRequired: true,
    _id: "5c2f96eba3f926162eb15bc8",
    supportType: "5c2f96eba3f926162eb15bc2",
    questionText: "Known organisation name",
    helperText: "How is your organisation generally referred?",
    inputType: "text",
    section: "Basic Info",
    __v: 0,
  },
  {
    isRequired: false,
    _id: "5c2f96eba3f926162eb15bc9",
    supportType: "5c2f96eba3f926162eb15bc2",
    questionText: "Organisation Type",
    options: [
      "Public sector",
      "private sector (for profit)",
      "private sector (not for profit)",
      "charity",
      "other",
    ],
    inputType: "radio",
    section: "Basic Info",
    __v: 0,
  },
  {
    isRequired: false,
    _id: "5c2f96eba3f926162eb15bca",
    supportType: "5c2f96eba3f926162eb15bc2",
    questionText: "Organisation URL",
    helperText: "Please include full URL (i.e. including https://)",
    inputType: "url",
    section: "Basic Info",
    __v: 0,
  },
  {
    isRequired: false,
    _id: "5c2f96eba3f926162eb15bcb",
    supportType: "5c2f96eba3f926162eb15bc2",
    questionText: "Organisation photo or logo",
    helperText: "Please no larger than 1mb and ideally square",
    inputType: "file-upload",
    section: "Basic Info",
    __v: 0,
  },
  {
    isRequired: true,
    _id: "5c2f96eba3f926162eb15bcc",
    supportType: "5c2f96eba3f926162eb15bc2",
    questionText: "Please provide a brief description of the organisation",
    helperText:
      "Keep it fact based and just describe what the organisation is, why it exists and what it does",
    inputType: "textarea",
    section: "Basic Info",
    __v: 0,
  },
]

const routes = {
  "/get-register-questions": questionData,
}

module.exports = {
  get: url => Promise.resolve({ data: routes[url] }),
}
